### ISSUE TITLE
TypeError in socket.bind

### ISSUE THREAD

**Issue by JavierNR** [sfera-labs/pycom-modbus#2] opened 2019-10-30 07:50 UTC
Hello!
First, many thanks for tweaking original pycom lib, and share on github.

I'm using the library successfully with WiPy devices as Modbus TCP server, but there's some problem I can't find under another ESP32 board (olimex ESP32-POE) with micropython v1.11.
The exact same code works without problems under WiPy, but on micropython throws this error:

```
Traceback (most recent call last):
  File "main.py", line 47, in <module>
  File "modbus.py", line 44, in bind
  File "/lib/uModBus/tcp.py", line 144, in bind
TypeError: function takes 2 positional arguments but 1 were given
```
I've added a print over line 144 of tcp.py file In order to see if local_ip and local_port have correct values:

```
print("IP",local_ip,"PORT",local_port)
self._sock.bind(socket.getaddrinfo(local_ip, local_port)[0][-1])
```

local_ip and local_port have correct values, also checked socket.getaddrifo() returns the same tuple both with WiPy and Micropython. Further investigation seems that the error happens at line 145
`self._sock.listen()`

At the moment I'm trying, but I'm not obtaining good results. Perhaps newer usocket library breaks something?

Note that I'm following almost the same example as in repo sfera-labs/exo-sense-py-modbus.

Best regards

**Comment by giampiero7** [comment] 2019-10-30 17:15
Hello Javier,
Thanks for the report.
The error seems to point at the bind() function, but in the current documentation it looks like it takes the same arguments, i.e. just the address.
Unfortunately, I cannot test it right now on a board other that the Pycom...
I think you should report the issue to micropython or to the board you are using.
I'm going to close this issue, in case you find the issue is indeed relative to this repo feel free to open a new one :)
Thanks again, and let us know if you find a solution :)

**Closed as completed by giampiero7** 2019-10-30 17:15 UTC

**Comment by dasv** [comment] 2019-12-19 14:45
It seems that the new socket library takes a backlog argumentin the listen() function: the backlog is the number of connections that will be held in the queue while a client is already connected, any further connections will be dropped. So, it is as simple as calling listen() with an int argument that states the number of clients to be queued.
This seems to work:
`self._sock.bind(socket.getaddrinfo(local_ip, local_port)[0][-1])`
 `self._sock.listen(1)`
